name: babh_dnevnicite
description: БАБХ Дневниците — мобилно приложение за сканиране, съхранение и OCR разпознаване на документи.
publish_to: "none"
version: 1.0.1+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Document scanning and OCR
  document_scanner_flutter: ^0.2.7
  flutter_tesseract_ocr:
    path: plugins/flutter_tesseract_ocr/flutter_tesseract_ocr

  # Camera and image management
  camera: ^0.10.6
  image_picker: ^1.2.0

  # File system and viewing
  path_provider: ^2.1.5
  photo_view: ^0.14.0

dependency_overrides:
  photo_view: ^0.14.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/tessdata/
    - assets/tessdata/bul.traineddata
    - assets/tessdata_config.json