name: babh_dnevnicite
description: БАБХ Дневниците — мобилно приложение за сканиране, съхранение и OCR разпознаване на документи.
publish_to: "none"
version: 1.0.1+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Camera and image management
  camera: ^0.10.6
  image_picker: ^1.2.0
  image: ^4.3.0
  google_mlkit_document_scanner: ^0.4.0

  # File system and viewing
  path_provider: ^2.1.5
  photo_view: ^0.14.0

  amplify_flutter: ^1.8.0
  amplify_auth_cognito: ^1.8.0
  amplify_storage_s3: ^1.8.0

  # Network
  connectivity_plus: ^7.0.0
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.3

dependency_overrides:
  photo_view: ^0.14.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/